apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      containers:
      - name: master
        image: bitnami/redis:6.0.13
        ports:
        - containerPort: 6379
